// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTRlYEjDp3yUzPcnIMMiZ2LADN_BM2YHg',
    appId: '1:457219916678:web:06563d82e44564e878e207',
    messagingSenderId: '457219916678',
    projectId: 'bloc-aacb5',
    authDomain: 'bloc-aacb5.firebaseapp.com',
    storageBucket: 'bloc-aacb5.appspot.com',
    measurementId: 'G-R9DCZ729WS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN9_Aw4C9SpIMbbrek9PlD5Pl3Fzvnnzw',
    appId: '1:457219916678:android:39ee794d8bc5996578e207',
    messagingSenderId: '457219916678',
    projectId: 'bloc-aacb5',
    storageBucket: 'bloc-aacb5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzvjgGEZwadQv0UVddLEv25o2I2SVSdKo',
    appId: '1:457219916678:ios:3a5b19a74b8e205478e207',
    messagingSenderId: '457219916678',
    projectId: 'bloc-aacb5',
    storageBucket: 'bloc-aacb5.appspot.com',
    androidClientId: '457219916678-2jrqpce9ais9va2lqtjqcole9kdrqh7m.apps.googleusercontent.com',
    iosClientId: '457219916678-0g68p5lb7ne184u3ap5viklpvff9jhrm.apps.googleusercontent.com',
    iosBundleId: 'com.example.blocThree',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzvjgGEZwadQv0UVddLEv25o2I2SVSdKo',
    appId: '1:457219916678:ios:3a5b19a74b8e205478e207',
    messagingSenderId: '457219916678',
    projectId: 'bloc-aacb5',
    storageBucket: 'bloc-aacb5.appspot.com',
    androidClientId: '457219916678-2jrqpce9ais9va2lqtjqcole9kdrqh7m.apps.googleusercontent.com',
    iosClientId: '457219916678-0g68p5lb7ne184u3ap5viklpvff9jhrm.apps.googleusercontent.com',
    iosBundleId: 'com.example.blocThree',
  );
}
